export const products = [
    {
        id: 1,
        name: "Grilled Steak",
        price: 5000,
        image: "/asset/Burger.jpg",
        category: "Main Course",
    },
    {
        id: 2,
        name: "Margherita Pizza",
        price: 6500,
        image: "/asset/Bread.jpg",
        category: "Main Course",
    },
    {
        id: 3,
        name: "Caesar Salad",
        price: 8000,
        image: "/asset/Food1.jpg",
        category: "Salad",
    },
    {
        id: 4,
        name: "Spaghetti Carbonara",
        price: 16500,
        image: "/asset/Food.jpg",
        category: "Pasta",
    },
    {
        id: 5,
        name: "Sushi Platter",
        price: 20000,
        image: "/asset/Cake.jpg",
        category: "Japanese",
    },
    {
        id: 6,
        name: "Cheeseburger & Fries",
        price: 10000,
        image: "/asset/Cake1.jpg",
        category: "Fast Food",
    },
    {
        id: 7,
        name: "Tiramisu",
        price: 8500,
        image: "/asset/Fruit.jpg",
        category: "Dessert",
    },
    {
        id: 8,
        name: "Fresh Orange Juice",
        price: 5500,
        image: "/asset/Fruit1.jpg",
        category: "Beverage",
    },
    {
        id: 9,
        name: "Chocolate Lava Cake",
        price: 6000,
        image: "/asset/Vegetable.jpg",
        category: "Dessert",
    },
];
